"""create new database

Revision ID: 12f4ca5ffcdf
Revises: 53e126254564
Create Date: 2026-03-18 10:16:21.755957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12f4ca5ffcdf'
down_revision: Union[str, Sequence[str], None] = '53e126254564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'user_type_id')
    )
    op.create_table('game_player',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('teacher_sport',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('team_player',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'player_id')
    )
    op.create_table('tournament_participant',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('tournament_id', 'player_id')
    )
    op.drop_table('teachersport')
    op.drop_table('gameplayer')
    op.drop_table('userrole')
    op.drop_table('tournamentparticipant')
    op.drop_table('teamplayer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teamplayer',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('teamplayer_player_id_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('teamplayer_team_id_fkey')),
    sa.PrimaryKeyConstraint('team_id', 'player_id', name=op.f('teamplayer_pkey'))
    )
    op.create_table('tournamentparticipant',
    sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('tournamentparticipant_player_id_fkey')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], name=op.f('tournamentparticipant_tournament_id_fkey')),
    sa.PrimaryKeyConstraint('tournament_id', 'player_id', name=op.f('tournamentparticipant_pkey'))
    )
    op.create_table('userrole',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('userrole_user_id_fkey')),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.id'], name=op.f('userrole_user_type_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'user_type_id', name=op.f('userrole_pkey'))
    )
    op.create_table('gameplayer',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('gameplayer_game_id_fkey')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('gameplayer_player_id_fkey')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('gameplayer_team_id_fkey')),
    sa.PrimaryKeyConstraint('game_id', 'player_id', name=op.f('gameplayer_pkey'))
    )
    op.create_table('teachersport',
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('teachersport_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('teacher_id', name=op.f('teachersport_pkey'))
    )
    op.drop_table('tournament_participant')
    op.drop_table('team_player')
    op.drop_table('teacher_sport')
    op.drop_table('game_player')
    op.drop_table('user_role')
    # ### end Alembic commands ###
