"""create auth_user table

Revision ID: 37f2e223210d
Revises: 12f4ca5ffcdf
Create Date: 2026-03-27 14:12:53.845215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f2e223210d'
down_revision: Union[str, Sequence[str], None] = '12f4ca5ffcdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=None), nullable=False),
    sa.Column('password_hash', sa.String(length=None), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_foreign_key(None, 'admin', 'auth_user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'club', 'auth_user', ['owner_id'], ['id'])
    op.add_column('game', sa.Column('name', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'game', 'auth_user', ['organizer_id'], ['id'])
    op.create_foreign_key(None, 'player', 'auth_user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'teacher', 'auth_user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tournament', 'auth_user', ['organizer_id'], ['id'])
    op.create_foreign_key(None, 'user_role', 'auth_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'tournament', type_='foreignkey')
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'name')
    op.drop_constraint(None, 'club', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
