"""create new database

Revision ID: 98cb31df1b20
Revises: 12f4ca5ffcdf
Create Date: 2026-03-18 10:44:04.348470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98cb31df1b20'
down_revision: Union[str, Sequence[str], None] = '12f4ca5ffcdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_players_per_team', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=None), nullable=False),
    sa.Column('city', sa.String(length=None), nullable=False),
    sa.Column('description', sa.String(length=None), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_id'), 'club', ['id'], unique=False)
    op.create_table('court',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price_per_hour', sa.Float(), nullable=False),
    sa.Column('is_indoor', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_court_id'), 'court', ['id'], unique=False)
    op.add_column('game', sa.Column('sport_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'game', 'sports', ['sport_id'], ['id'])
    op.add_column('teacher_sport', sa.Column('sport_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teacher_sport', 'sports', ['sport_id'], ['id'])
    op.add_column('team', sa.Column('sport_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team', 'sports', ['sport_id'], ['id'])
    op.add_column('tournament', sa.Column('sport_id', sa.Integer(), nullable=False))
    op.add_column('tournament', sa.Column('club_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournament', 'sports', ['sport_id'], ['id'])
    op.create_foreign_key(None, 'tournament', 'club', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament', type_='foreignkey')
    op.drop_constraint(None, 'tournament', type_='foreignkey')
    op.drop_column('tournament', 'club_id')
    op.drop_column('tournament', 'sport_id')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'sport_id')
    op.drop_constraint(None, 'teacher_sport', type_='foreignkey')
    op.drop_column('teacher_sport', 'sport_id')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'sport_id')
    op.drop_index(op.f('ix_court_id'), table_name='court')
    op.drop_table('court')
    op.drop_index(op.f('ix_club_id'), table_name='club')
    op.drop_table('club')
    op.drop_table('sports')
    # ### end Alembic commands ###
