import 'package:flutter/material.dart';

/// ColorSchemes del sistema "Club de barrio moderno" — verde pino profundo
/// sobre neutros cálidos (crema, no blanco clínico): "tarde de cancha,
/// tercer tiempo, mate en el banco". Manuales a propósito (nada de
/// fromSeed): cada rol es una decisión, y el dark mode está diseñado a
/// mano con superficies verde-cálidas, no invertido.
/// Contrastes verificados AA (texto normal ≥ 4.5) en ambos modos.
abstract final class AppSchemes {
  static const light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF1E4D40),
    onPrimary: Colors.white,
    primaryContainer: Color(0xFFCDE6D8),
    onPrimaryContainer: Color(0xFF0E2E24),
    secondary: Color(0xFF55604A),
    onSecondary: Colors.white,
    secondaryContainer: Color(0xFFDFE5CF),
    onSecondaryContainer: Color(0xFF2A3322),
    tertiary: Color(0xFF7A5900),
    onTertiary: Colors.white,
    tertiaryContainer: Color(0xFFFFC24B),
    onTertiaryContainer: Color(0xFF3D2E00),
    error: Color(0xFFB3362E),
    onError: Colors.white,
    errorContainer: Color(0xFFF8DAD2),
    onErrorContainer: Color(0xFF7C221C),
    surface: Color(0xFFFAF6EE),
    onSurface: Color(0xFF211D12),
    surfaceContainerLowest: Colors.white,
    surfaceContainerLow: Color(0xFFF5F0E2),
    surfaceContainer: Color(0xFFF0EAD9),
    surfaceContainerHigh: Color(0xFFEBE4CF),
    surfaceContainerHighest: Color(0xFFE5DDC5),
    onSurfaceVariant: Color(0xFF55503E),
    outline: Color(0xFF837B66),
    outlineVariant: Color(0xFFDBD2BB),
    shadow: Colors.black,
    scrim: Colors.black,
    inverseSurface: Color(0xFF211D12),
    onInverseSurface: Color(0xFFFAF6EE),
    inversePrimary: Color(0xFF8ACFB0),
  );

  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF8ACFB0),
    onPrimary: Color(0xFF0A2C20),
    primaryContainer: Color(0xFF24473B),
    onPrimaryContainer: Color(0xFFC9E9D9),
    secondary: Color(0xFFB8C2A6),
    onSecondary: Color(0xFF242E1B),
    secondaryContainer: Color(0xFF39442E),
    onSecondaryContainer: Color(0xFFDFE5CF),
    tertiary: Color(0xFFFFC24B),
    onTertiary: Color(0xFF3D2E00),
    tertiaryContainer: Color(0xFF4A3800),
    onTertiaryContainer: Color(0xFFFFDFA0),
    error: Color(0xFFFF9284),
    onError: Color(0xFF3C120C),
    errorContainer: Color(0xFF45211B),
    onErrorContainer: Color(0xFFFFD0C7),
    surface: Color(0xFF14201C),
    onSurface: Color(0xFFEAE6D9),
    surfaceContainerLowest: Color(0xFF0F1915),
    surfaceContainerLow: Color(0xFF182420),
    surfaceContainer: Color(0xFF1B2823),
    surfaceContainerHigh: Color(0xFF21302A),
    surfaceContainerHighest: Color(0xFF283A32),
    onSurfaceVariant: Color(0xFFA9B2A0),
    outline: Color(0xFF6E7A6C),
    outlineVariant: Color(0xFF2C3A32),
    shadow: Colors.black,
    scrim: Colors.black,
    inverseSurface: Color(0xFFEAE6D9),
    onInverseSurface: Color(0xFF211D12),
    inversePrimary: Color(0xFF1E4D40),
  );
}
